Repository StoicNeutron/TrackMyWorkout_Server, pull requests merged in 2023-12, with the labels that each got.

#6 close 5 implement user and user controller
  build.gradle
  build/classes/java/main/com/TrackMyWorkout/Server/User/User.class
  build/classes/java/main/com/TrackMyWorkout/Server/User/UserController.class
  build/resources/main/application.properties
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/TrackMyWorkout/Server/User/User.java
  src/main/java/com/TrackMyWorkout/Server/User/UserController.java
  src/main/resources/application.properties
Labels: enhancement

#8 close implement JPA
  build/classes/java/main/com/TrackMyWorkout/Server/User/User.class
  build/classes/java/main/com/TrackMyWorkout/Server/User/UserController.class
  build/classes/java/main/com/TrackMyWorkout/Server/User/UserRepository.class
  build/classes/java/main/com/TrackMyWorkout/Server/User/UserService.class
  build/resources/main/application.properties
  build/tmp/compileJava/compileTransaction/stash-dir/User.class.uniqueId2
  build/tmp/compileJava/compileTransaction/stash-dir/UserController.class.uniqueId3
  build/tmp/compileJava/compileTransaction/stash-dir/UserRepository.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/UserService.class.uniqueId0
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/TrackMyWorkout/Server/User/User.java
  src/main/java/com/TrackMyWorkout/Server/User/UserController.java
  src/main/java/com/TrackMyWorkout/Server/User/UserRepository.java
  src/main/java/com/TrackMyWorkout/Server/User/UserService.java
  src/main/resources/application.properties
Labels: enhancement

#13 restructure MVC and add auth endpoint
  build.gradle
  build/classes/java/main/com/TrackMyWorkout/Server/Controllers/UserController.class
  build/classes/java/main/com/TrackMyWorkout/Server/DTO/LoginRequestDTO.class
  build/classes/java/main/com/TrackMyWorkout/Server/Entities/User.class
  build/classes/java/main/com/TrackMyWorkout/Server/Repositories/UserRepository.class
  build/classes/java/main/com/TrackMyWorkout/Server/Services/UserService.class
  build/classes/java/main/com/TrackMyWorkout/Server/User/User.class
  build/classes/java/main/com/TrackMyWorkout/Server/User/UserController.class
  build/classes/java/main/com/TrackMyWorkout/Server/User/UserRepository.class
  build/classes/java/main/com/TrackMyWorkout/Server/User/UserService.class
  build/tmp/compileJava/compileTransaction/stash-dir/User.class.uniqueId2
  build/tmp/compileJava/compileTransaction/stash-dir/UserController.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/UserController.class.uniqueId3
  build/tmp/compileJava/compileTransaction/stash-dir/UserRepository.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/UserService.class.uniqueId0
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/TrackMyWorkout/Server/Controllers/UserController.java
  src/main/java/com/TrackMyWorkout/Server/DTO/LoginRequestDTO.java
  src/main/java/com/TrackMyWorkout/Server/Entities/User.java
  src/main/java/com/TrackMyWorkout/Server/Repositories/UserRepository.java
  src/main/java/com/TrackMyWorkout/Server/Services/UserService.java
  src/main/java/com/TrackMyWorkout/Server/User/UserController.java
  src/main/java/com/TrackMyWorkout/Server/User/UserRepository.java
Labels: documentation, enhancement

#15 correct endpoint implementation
  build/classes/java/main/com/TrackMyWorkout/Server/Controllers/UserController.class
  build/classes/java/main/com/TrackMyWorkout/Server/DTO/SignUpRequestDTO.class
  build/classes/java/main/com/TrackMyWorkout/Server/Entities/User.class
  build/tmp/compileJava/compileTransaction/stash-dir/SignUpRequest.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/UserController.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/UserController.class.uniqueId1
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/TrackMyWorkout/Server/Controllers/UserController.java
  src/main/java/com/TrackMyWorkout/Server/DTO/LoginRequestDTO.java
  src/main/java/com/TrackMyWorkout/Server/DTO/SignUpRequestDTO.java
  src/main/java/com/TrackMyWorkout/Server/Entities/User.java
  src/main/java/com/TrackMyWorkout/Server/Repositories/UserRepository.java
  src/main/java/com/TrackMyWorkout/Server/Services/UserService.java
Labels: documentation
